### ISSUE TITLE
HOWTO:  discover base address of the bank of error registers

### ISSUE THREAD

**Issue by billmcspadden-riscv** [riscv/riscv-ras-eri#6]
What is the mechanism used to determine the base address of the bank of registers?
Will a CSR be defined?   Is it a SW-only managed address?

Context for this question:  if I were to implement RERI functionality in the Sail model,
where would I get the address information so I can configure the Sail model?

**Comment by ved-rivos** [comment]
No CSR will be defined. The base address discovery for the bank of registers should follow the unified discovery mechanism. There may not be a single base address in the system and the error banks implemented by the system do not need to be contiguous in address space. Discovering of base addresses for these registers should follow as done for other non-ISA registers such as those of a PLIC/APLIC, IMSIC, etc.
